### ISSUE TITLE
Error when launching seafile container

### ISSUE THREAD

**Issue by dalareo** [podshumok/docker-seafile#1]
I get:

```
Generating seafile configuration ...

Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/local/seafile/seafile-server/makedb.py", line 102, in <module>
ssm.seafile_config.generate()
File "ssm.py", line 903, in generate
if Utils.run_argv(argv, env=env_mgr.get_binary_env()) != 0:
File "ssm.py", line 84, in run_argv
env=env)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
TypeError: coercing to Unicode: need string or buffer, NoneType found
sed: can't read /usr/local/seafile/ccnet/ccnet.conf: No such file or directory

-------------------------------------------------------------
This script would do the minor upgrade for you.
Press [ENTER] to contiune
-------------------------------------------------------------


------------------------------
migrating avatars ...


Error: avatars directory "/usr/local/seafile/seahub-data/avatars" does not exist


/usr/local/seafile/ccnet/seafile.ini not found. Now quit
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
mod_name, _Error)
File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
code = loader.get_code(mod_name)
File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
self.code = compile(source, self.filename, 'exec')
File "/usr/local/seafile/seafile-server/prepare_.py", line 6
check_init_admin.create_admin(admin@example.com),
                                   ^
SyntaxError: invalid syntax

/usr/local/seafile/ccnet/seafile.ini not found. Now quit

/usr/local/seafile/ccnet/seafile.ini not found. Now quit
```

**Comment by code-of-kpp** [comment]
Hello. Thank you for reporting!

I've tried to update major version. That broke some things, including building itself, startup and probably a lot more.

Yesterday I fixed image building and today I fixed startup...

Please test, review default values and so on...

**Comment by dalareo** [comment]
Great! I will check out the changes you made. Right now I am using https://github.com/JensErat/docker-seafile with Sqlite for my project, @educaas, but I want to implement NGINX reverse proxy.
